export const MAX_DOCUMENT_FILE_SIZE_BYTES = 300 * 1024 * 1024;
export const MAX_DOCUMENT_CHUNKS_PER_APPEND = 500;
export const DOCUMENT_EMBEDDING_DIMENSIONS = 1536;
export const MAX_DOCUMENT_CHUNK_EMBEDDINGS_PER_APPEND = 100;
