export const MAX_PROJECT_SLUG_LENGTH = 60;
export const PROJECT_SLUG_RANDOM_DIGITS = 9;
export const MAX_PROJECT_SLUG_BASE_LENGTH =
  MAX_PROJECT_SLUG_LENGTH - PROJECT_SLUG_RANDOM_DIGITS - 1;
export const PROJECT_EMBEDDING_DIMENSIONS = 1536;
